# Generated code do not commit.
file(TO_CMAKE_PATH "E:\\flutter" FLUTTER_ROOT)
file(TO_CMAKE_PATH "E:\\U_Hack_FormaOS-1\\flutter_app" PROJECT_DIR)

set(FLUTTER_VERSION "1.0.0+1" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 1 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 0 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 1 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=E:\\flutter"
  "PROJECT_DIR=E:\\U_Hack_FormaOS-1\\flutter_app"
  "FLUTTER_ROOT=E:\\flutter"
  "FLUTTER_EPHEMERAL_DIR=E:\\U_Hack_FormaOS-1\\flutter_app\\windows\\flutter\\ephemeral"
  "PROJECT_DIR=E:\\U_Hack_FormaOS-1\\flutter_app"
  "FLUTTER_TARGET=E:\\U_Hack_FormaOS-1\\flutter_app\\lib\\main.dart"
  "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuNDEuNw==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049Y2MwNzM0YWM3MQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049NTlhYTU4NGZkZg==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMS41"
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=E:\\U_Hack_FormaOS-1\\flutter_app\\.dart_tool\\package_config.json"
)
